name: Build ACAP

on:
  push:
    branches: [master, main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Build .eap package
        run: docker buildx build --build-arg ARCH=aarch64 --target artifact --output type=local,dest=build .

      - name: Locate package
        run: find build -name "*.eap" -exec ls -la {} \;

      - name: Upload .eap artifact
        uses: actions/upload-artifact@v7
        with:
          name: sds3sync-eap
          path: build/*.eap
          if-no-files-found: error
